# Generated by Django 5.0.2 on 2025-06-01 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0002_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dds_record',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serv.subcategory'),
        ),
        migrations.AddField(
            model_name='dds_record',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serv.type'),
        ),
    ]
